export enum Signals {
  JOIN_ROOM = "JOIN_ROOM",
  JOIN_ROOM_SUCCESS = "JOIN_ROOM_SUCCESS",
  JOIN_ROOM_FAILURE = "JOIN_ROOM_FAILURE",

  LOAD_GAME_DATA = "LOAD_GAME_DATA",
  PLAYER_JOINED = "PLAYER_JOINED",
  PLAYER_LEFT = "PLAYER_LEFT",
}
