export enum Signals {
  JOIN_ROOM = "JOIN_ROOM",
  JOIN_ROOM_SUCCESS = "JOIN_ROOM_SUCCESS",
  JOIN_ROOM_FAILURE = "JOIN_ROOM_FAILURE",

  LOAD_GAME_DATA = "LOAD_GAME_DATA",
  PLAYER_JOINED = "PLAYER_JOINED",
  PLAYER_LEFT = "PLAYER_LEFT",

  SET_PLAYER_DIRECTION = "SET_PLAYER_DIRECTION",
  UPDATE_GAME = "UPDATE_GAME",
}
